---
    version: '2'
    
    services:
      ca.rzd.rails.rzd:
        image: hyperledger/fabric-ca:latest
        environment:
          - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
          - FABRIC_CA_SERVER_CA_NAME=ca-rzd
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_PORT=7054
        ports:
          - "7054:7054"
        command: sh -c 'fabric-ca-server start  -b admin:adminpw -d'
        container_name: ca.rzd.rails.rzd
        volumes:
          - /home/user/example/config-rzd/crypto-config/fabric-ca/rzd:/etc/hyperledger/fabric-ca-server
    
      # ca.orderer.rails.rzd:
      #   image: hyperledger/fabric-ca:latest
      #   environment:
      #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      #     - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      #     - FABRIC_CA_SERVER_TLS_ENABLED=true
      #     - FABRIC_CA_SERVER_PORT=7054
      #   ports:
      #     - "8054:7054"
      #   command: sh -c 'fabric-ca-server start  -b admin:adminpw -d'
      #   container_name: ca.orderer.rails.rzd
      #   volumes:
      #     - /home/user/example/config-rzd/crypto-config/fabric-ca/orderer:/etc/hyperledger/fabric-ca-server
    