---
version: '2'

services:
  ca.rzd2.rails.rzd:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-rzd2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start  -b admin:adminpw -d'
    container_name: ca.rzd2.rails.rzd
    volumes:
      - /home/user/example/config-rzd2/crypto-config/fabric-ca/rzd2:/etc/hyperledger/fabric-ca-server

  # ca.orderer2.rails.rzd:
  #   image: hyperledger/fabric-ca:latest
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-orderer2
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=7054
  #   ports:
  #     - "8054:7054"
  #   command: sh -c 'fabric-ca-server start  -b admin:adminpw -d'
  #   container_name: ca.orderer2.rails.rzd
  #   volumes:
  #     - /home/user/example/config-rzd2/crypto-config/fabric-ca/orderer2:/etc/hyperledger/fabric-ca-server
