version: '2'

services:

  peer0.rzd2.rails.rzd:
    container_name: peer0.rzd2.rails.rzd
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker-templates.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dockercompose_default
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.rzd2.rails.rzd
      - CORE_PEER_ADDRESS=peer0.rzd2.rails.rzd:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rzd2.rails.rzd:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rzd2.rails.rzd:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rzd2.rails.rzd:7051
      - CORE_PEER_LOCALMSPID=rzd2MSP
    ports:
      - 7051:7051
    volumes:
      - /var/run/:/host/var/run/
      - /home/user/example/config-rzd2/crypto-config/peerOrganizations/rzd2.rails.rzd/peers/peer0.rzd2.rails.rzd/msp:/etc/hyperledger/fabric/msp
      - /home/user/example/config-rzd2/crypto-config/peerOrganizations/rzd2.rails.rzd/peers/peer0.rzd2.rails.rzd/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    extra_hosts:
      -  orderer.rails.rzd:142.93.139.226
      -  peer0.rzd.rails.rzd:142.93.139.226
      -  orderer3.rails.rzd:142.93.131.119
      -  peer0.rzd3.rails.rzd:142.93.131.119

  couchdb.rzd2.rails.rzd:
    container_name: couchdb.rzd2.rails.rzd
    image: hyperledger/fabric-couchdb:latest
    restart: always
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  # environment:
    #  - COUCHDB_USER=user123
    #  - COUCHDB_PASSWORD=password123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 5984:5984
